### ISSUE TITLE
Unable to get dockerfile of base image "appsvcorg/nginx-fpm:0.2" & Is this supports azure SSH

### ISSUE THREAD

**Issue by asagi3** [Azure-App-Service/drupal-nginx-fpm#8]
Unable to get dockerfile of base image "appsvcorg/nginx-fpm:0.2" & Is this supports azure SSH

As we may need to customize/review the base sometime we need to need to have the base image dockerfile available

**Comment by LeonZhang77** [comment]
we keep maintaining nginx-fpm image in below repo, please try latest version.

https://github.com/Azure/app-service-quickstart-docker-images
