### ISSUE TITLE
Drush not working

### ISSUE THREAD

**Issue by mariojacobo** [Azure-App-Service/drupal-nginx-fpm#9]
We can't seem to get drush working on this default image. It shows up as installed, but there is no output whatsoever: 

root@3ed88c28aae2:~# which drush
/usr/local/bin/drush
root@3ed88c28aae2:~# drush --version
root@3ed88c28aae2:~# drush version
root@3ed88c28aae2:~# drush info
root@3ed88c28aae2:~# drush sql-cli
root@3ed88c28aae2:~#

**Comment by LeonZhang77** [comment]
https://github.com/Azure/app-service-quickstart-docker-images.

we keep maintain drupal-nginx-fpm images in above repo, the latest version is appsvcorg/drupal-nginx-fpm:0.46.
